# noinspection SpellCheckingInspection
app:
  log_level: DEBUG
  emby_url: http://127.0.0.1:8096
  emby_api_key: 
  backend_url: 
  backend_token: 
  alist_url:
  alist_api_key:
  ua_allow_list:
    - Tsukimi
    - Yamby
    - Emby
    - infuse-direct
    - iemc
    - PotPlayer
    - libmpv
    - mpv
    - Fileball
    - yybx
    - VLC
    - Conflux
    - EmbyTheater
    - Terminus
    - SenPlayer
    - MXPlayer
    - iPlayClient
    - IINA
    - nPlayer
    - XstarPlayer
    - AppleCoreMedia
  web_ua_allow_list:
    - Mozilla
    - Opera
  national_memorial_day_stream_path: 
  september_18th_incident_stream_path: 
  forbidden_ua_stream_path: 